systemNamespace: kyma-system
selfSignedIssuer: cfapi-self-signed-issuer
useSelfSignedCertificates: false
cfDomain:

containerRegistrySecret:
  name: dockerregistry-config
  propagation:
    enabled: false
    sourceNamespace:
    destinationNamespace:
