broker:
  image: ghcr.io/kyma-project/cfapi/btp-service-broker
  imagePullSecret: dockerregistry-config-external
  port: 8080
  resourceNamespace: cfapi-system
  credentials:
    username: broker-user
    password: broker-password

korifi:
  rootNamespace: cf
